# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]
jobs:
  test-coverage:
    name: Test on latest NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm run test-coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
  test-node-lts:
    name: Test on NodeJS 20 (LTS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codd
        uses: actions/checkout@v4
      - name: Use Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

